### ISSUE TITLE
Create section for the golang client API.

### ISSUE THREAD

**Issue by johnnymatthews** [drand/website#12]
drand/drand#554 creates a `readme.md` in the `/clients` folder to explain the different clients and composition options. This readme should be brought into the docs too.

**Comment by willscott** [comment]
ref: https://github.com/drand/drand/issues/554

**Comment by alanshaw** [comment]
There is now sections for both the Go and JS clients however the team opted to keep the usage examples along with the API docs in the respective repos. e.g. https://github.com/drand/drand/pull/722
