### ISSUE TITLE
Move away from Google Universal Analytics

### ISSUE THREAD

**Issue by AnomalRoil** [drand/website#126]
Since it's being sunset and Google Analytics 4 is replacing it in 2023.

**Comment by johnnymatthews** [comment]
If you don't wanna use Google Analytics anymore, take a look at [Plausible](https://plausible.io/sites)! I use it on my personal sites, and I'm testing it out for a couple Protocol Labs sites too.

**Comment by ErickWa** [comment]
Completed by johnnymatthews on 06/15/23
