### ISSUE TITLE
Simple install link is broken

### ISSUE THREAD

**Issue by LesnyRumcajs** [drand/website#131]
The simple install link [here](https://drand.love/operator/docker/#install-drand-with-docker) is broken, i.e. https://drand.love/install results in `ipfs resolve -r /ipfs/bafybeibh577ymwr4dyjnvokhrilaqocgt2mrvzr4zi3adapu4hdekywm5q/install: no link named "install" under bafybeibh577ymwr4dyjnvokhrilaqocgt2mrvzr4zi3adapu4hdekywm5q`

**Comment by Annamarie2019** [comment]
Find the current link to install Docker and correct.

**Comment by Annamarie2019** [comment]
@johnnymatthews  I was about to triage, but I can't label in the drand website
