### ISSUE TITLE
Treat root of website as more of a homepage, rather than a documentation platform.

### ISSUE THREAD

**Issue by jsoares** [drand/website#14]
Given this will be the main web presence for drand and not _just_ a documentation subdomain, it would be great if the homepage were a little more engaging.

I don't have a clear idea of how to make this happen but options include:
- Some more intro text, rather than a short paragraph followed by docs links
- A widget showing the current drand random value
- More images (e.g. a link to the [LoE](https://leagueofentropy.com/) using its logo, as the reference deployment)
- Embedding Nicolas' [drand talk](https://www.youtube.com/watch?v=ydwW2HFFxNI) as an intro to the project

**Comment by nikkolasg** [comment]
+1 for this
