### ISSUE TITLE
HTTP-API documentation wrong

### ISSUE THREAD

**Issue by ranok** [drand/website#143]
Following the URIs from the documentation gives in many cases either a 404 or a Forbidden error. 

For example https://api2.drand.sh/chains returns a 404, and the {chain-hash}/* tree of API endpoints also returns 404.

**Comment by mcamou** [comment]
@yiannisbot not sure what to do here, is it a documentation error, or is the documentation correct and something needs to be fixed?

**Comment by AnomalRoil** [comment]
This was because the mainnet nodes were not yet using the new v1.4 version.
We have now released it on Mainnet and it should work.
