### ISSUE TITLE
Add a League of Entropy dedicated page

### ISSUE THREAD

**Issue by AnomalRoil** [drand/website#161]
In order to have a URL to refer easily to the League of Entropy.

**Comment by ErickWa** [comment]
Were you thinking of cloning Cloudflare's LoE page, but placing it at drand.love/leagueofentropy?  If not, do you have any thoughts about content?  I can whip up an .md file with stuff if needed.

**Comment by ErickWa** [comment]
Completed at https://leagueofentropy.org
