### ISSUE TITLE
Add "How to install with Docker" section.

### ISSUE THREAD

**Issue by jsoares** [drand/website#17]
Right now, the deploying drand page links to Github for [docker deployment instruction](https://github.com/drand/drand/blob/master/docker/README.md). From talking to partners, this seems to be the most common way to deploy drand. It's probably worth moving the content into the docs website.

**Comment by johnnymatthews** [comment]
This section will fall under `drand.love/install/docker.

**Comment by jsoares** [comment]
Current status:
- The content seems to have been deleted from GitHub while moving to the website, 
- The [website](https://beta.drand.love/operator/deploy/#setup) still links to GitHub (404)

Do we have docker instructions available somewhere public? :/

**Comment by johnnymatthews** [comment]
[It exists](https://beta.drand.love/operator/docker/), but it's just not linked in the sidebar for some reason... [This PR fixes that](https://github.com/drand/website/pull/55).
