### ISSUE TITLE
Improve the outdated project page.

### ISSUE THREAD

**Issue by nikkolasg** [drand/website#19]
The text https://beta.drand.love/project/#project is outdated and incomplete; I'll try to come up with a re-written version here so we can iterate.

**Comment by johnnymatthews** [comment]
Nice, thanks for picking this up @nikkolasg. Feel free to add me as a reviewer.

**Comment by alanshaw** [comment]
Did this get done?

**Comment by alanshaw** [comment]
I'm guessing this was resolved by https://github.com/drand/website/pull/66
