### ISSUE TITLE
Homepage feedback

### ISSUE THREAD

**Issue by alanshaw** [drand/website#21]
Here's some feedback for the homepage that we can do easily and quickly to get it looking and working better for us:

1. We need to get the new logo on there ASAP to give it some identity and make it feel a little more professional. The dice emoji (while great) has served it's purpose! The "drand" lettering without the logo next to the dice is not looking great as it's not spaced/aligned correctly and is low resolution. We can drop in the latest design round for now and replace when the have the finals.
1. The getting started section should prioritise ways of consuming the service. Eventually the number of users consuming drand as a service will far outnumber operators so we should privilege access to this information. The call to action for operators should be moved to the "Get Involved" section.
    * We only have client libraries for golang and JS right now, so we need to give the docs for the HTTP API enough attention since this is the only solution for anyone wanting to use drand with _any_ other programming language.
1. The banner text needs some serious work! This needs to be short, descriptive and exciting. I came up with "Distributed Randomness Beacon. Verifiable, unpredictable and unbiased random numbers as a service." - could do with some tweaks I imagine but reads much better than what we have there atm right?
1. Link colours need to be something sensible and ideally taken from the pallette in the logo.
1. The favicon needs to be swaped out for the drand logo
1. The page title for the homepage needs to be something more like `<title>drand - distributed randomness beacon</title>`
1. We need to liven the design up a little to draw people in. Right now it feels like I'm looking at a tractor.
1. The current (live updating) randomness value needs to be on the homepage.

I'm by no means a designer but I knocked up a couple of possible homepage designs that incorporate most of this feedback and would also resolve https://github.com/drand/website/issues/14. I've just dropped eveything on the page by eye so the paddings and alignments are all off but you get the idea:

![hero](https://user-images.githubusercontent.com/152863/85536489-0d2a6880-b60b-11ea-9d6f-a6ff07a47af0.png)

Alternatively we could go a more simple route. Either way I think we could use the header for the internal pages:

![alt](https://user-images.githubusercontent.com/152863/85535844-765dac00-b60a-11ea-9a6e-ee63eebf9689.png)

I'm not sold on the buttons, but @akrych might be able to help me tidy them up a little 🙏?

Some other rough design things I'd really like to see on the homepage:

1. A nod to the "beacon" element of drand, either in the background for the hero or an icon or something. I was thinking something like the RSS feed icon.
1. Illustrations/icons for the HTTP API and the Client Libraries. I imagine there's something we have already that could be re-coloured/re-purposed for drand.
1. A generic glitchy background like https://docs.filecoin.io/images/main-page-background.png that could be used on other pages, in presentations etc.
1. I'd love an illustration for the different operators, their entropy sources (like I love the idea of entropy from cloudflare's lava lamp wall) and how it's converted into a randomness round and consumed by clients. THIS NEEDS DEFINING BETTER!
1. I read somewhere that someone suggested putting @nikkolasg's slides on the homepage. It would be great to get that presentation re-recorded with some on-brand slides.

**Comment by johnnymatthews** [comment]
This is great! Thanks for going through all this @alanshaw! I especially like the first mock up. To get this done though, we'll absolutely need a dedicated web developer to work on this for a couple of weeks.

**Comment by johnnymatthews** [comment]
Issues created from this issue: #24 #25 #26 #27 #28 #29 #30.
