### ISSUE TITLE
Prioritise ways of consuming drand, rather than operating nodes.

### ISSUE THREAD

**Issue by johnnymatthews** [drand/website#25]
The getting started section should prioritize ways of consuming the service. Eventually the number of users consuming drand as a service will far outnumber operators so we should privilege access to this information. The call to action for operators should be moved to the "Get Involved" section.

We only have client libraries for golang and JS right now, so we need to give the docs for the HTTP API enough attention since this is the only solution for anyone wanting to use drand with any other programming language.

**Comment by alanshaw** [comment]
resolved in https://github.com/drand/website/pull/20
