### ISSUE TITLE
Rename main navigation items

### ISSUE THREAD

**Issue by alanshaw** [drand/website#42]
@daviddias suggested the following renaming:

![image](https://user-images.githubusercontent.com/152863/86113343-0d21e100-bac1-11ea-8726-93ba5d0f2ed2.png)

**Comment by johnnymatthews** [comment]
We could remove the clutter and merge **Concepts** with **About**.

```
Docs
	Drand.js
	...
	
Operate
	Deploy a drand network
	Drand metrics
	Drand command-line tools

About
	Cryptography
	Security Model
	Specification
	Community
	Contributing
	Status [>]
	
GitHub [>]
```

**Comment by alanshaw** [comment]
IMHO there's value in keeping the separation between how it works (proposed "Docs"), how to use it ("Developer" and "Operator"), and how it's organised ("About").

The github link will move to the footer soon anyway so there'll only be 4 items in the main nav.

**Comment by johnnymatthews** [comment]
Fair enough. Happy to go with @daviddias's suggestion then.

**Comment by alanshaw** [comment]
Resolved by https://github.com/drand/website/pull/20/commits/d278a8ad529a69856a6edcf0714f3bf322f8749d
