### ISSUE TITLE
Dissociate this repo from ipfs/ipfs-docs.

### ISSUE THREAD

**Issue by yusefnapora** [drand/website#5]
I just noticed that if you open a PR against this repo, github uses the master branch of `ipfs/ipfs-docs` as the base branch. I guess this is because we forked this repo off of ipfs-docs.

This [SO answer](https://stackoverflow.com/a/45637149/1292992) says we can contact github support to dissociate from the ipfs repo, or we could recreate this one as a new repo.

**Comment by johnnymatthews** [comment]
I've submitted a ticket to GitHub support. Hopefully they'll get back to us soon.

**Comment by johnnymatthews** [comment]
Haha, it took them maybe 4 minutes to reply to my ticket. This repo is now it's own thing :)
