### ISSUE TITLE
Enhance LoE homepage section

### ISSUE THREAD

**Issue by alanshaw** [drand/website#56]
Suggestion from @nikkolasg:

> (1) a box to go back and forward to see it's a chain and (2) clicking on it could show the raw JSON output of the response so ppl have an idea of what it looks like.

Suggestion from @daviddias:

> how the list of partners is presented (ideas: have carousel of logos, hyperlink to their own websites)

**Comment by jsoares** [comment]
Should also link to leagueofentropy.com
