### ISSUE TITLE
Add section to homepage - drand users

### ISSUE THREAD

**Issue by alanshaw** [drand/website#86]
Logos of (high profile?) organisations that are using drand in their applications. This should give people thinking about using drand more confidence to do so.

**Comment by daviddias** [comment]
Great idea! Just to keep track of things:

- https://github.com/CosmWasm/drand-verify
- ETH2 Trusted Setup 
- Filecoin Trusted Setup
- Filecoin Mainnet

**Comment by alanshaw** [comment]
😂 I forgot to say, this was @daviddias's idea. It _IS_ a great idea.
